services:
  - type: web
    name: rif-activator-a12plus
    env: python
    plan: free
    buildCommand: pip install -r requirements_render.txt
    startCommand: gunicorn --config gunicorn_config.py wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
    healthCheckPath: /api/status